In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display plots in-notebook
%matplotlib inline

# Increase default figure and font sizes for easier viewing.
plt.rcParams['figure.figsize'] = (8, 6)
plt.rcParams['font.size'] = 14

loc = './impaired-driving-death-rate-by-age-and-gender-2012-2014-all-states.csv'
data = pd.read_csv(loc)

In [4]:
data

,State,Location,"All Ages, 2012","All Ages, 2014","Ages 0-20, 2012","Ages 0-20, 2014","Ages 21-34, 2012","Ages 21-34, 2014","Ages 35+, 2012","Ages 35+, 2014","Male, 2012","Male, 2014","Female, 2012","Female, 2014"
0,United States,"{'human_address': '{""address"":""United States"",...",3.3,3.1,1.3,1.2,6.7,6.2,3.1,3.0,5.2,4.9,1.5,1.4
1,Alabama,"{'human_address': '{""address"":""Alabama"",""city""...",5.5,5.5,2.7,2.1,10.3,10.0,5.0,5.5,8.4,8.6,2.9,2.6
2,Alaska,"{'human_address': '{""address"":""Alaska"",""city"":...",NaN,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arizona,"{'human_address': '{""address"":""Arizona"",""city""...",3.6,3.0,1.6,NaN,6.9,5.5,3.3,3.1,5.4,4.5,1.7,1.5
4,Arkansas,"{'human_address': '{""address"":""Arkansas"",""city...",5.1,4.6,NaN,NaN,10.5,6.3,4.3,5.4,8.1,7.2,2.2,2.2
5,California,"{'human_address': '{""address"":""California"",""ci...",2.0,2.2,0.9,1.0,4.5,4.6,1.8,2.0,3.2,3.4,1.0,1.1
6,Colorado,"{'human_address': '{""address"":""Colorado"",""city...",2.5,3.0,NaN,1.7,5.6,5.6,2.0,2.6,3.9,4.6,1.1,1.3
7,Connecticut,"{'human_address': '{""address"":""Connecticut"",""c...",2.4,2.7,NaN,NaN,5.9,6.1,2.1,2.5,3.7,4.6,1.1,NaN
8,Delaware,"{'human_address': '{""address"":""Delaware"",""city...",3.8,5.2,NaN,NaN,NaN,11.7,4.0,4.6,6.6,7.4,NaN,NaN
9,District of Columbia,"{'human_address': '{""address"":""District of Col...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Florida,"{'human_address': '{""address"":""Florida"",""city""...",3.7,3.5,1.2,1.2,8.0,7.4,3.3,3.1,5.7,5.4,1.7,1.7
11,Georgia,"{'human_address': '{""address"":""Georgia"",""city""...",3.0,2.7,1.0,0.8,5.8,5.2,3.1,2.9,4.9,4.7,1.2,0.9
12,Hawaii,"{'human_address': '{""address"":""Hawaii"",""city"":...",3.8,2.2,NaN,NaN,NaN,NaN,3.2,NaN,5.7,3.6,NaN,NaN
13,Idaho,"{'human_address': '{""address"":""Idaho"",""city"":""...",3.6,3.3,NaN,NaN,8.7,NaN,2.7,3.0,5.8,4.8,NaN,NaN
14,Illinois,"{'human_address': '{""address"":""Illinois"",""city...",2.5,2.4,0.7,0.7,6.0,5.5,2.1,2.2,4.0,3.7,1.0,1.3
15,Indiana,"{'human_address': '{""address"":""Indiana"",""city""...",3.6,3.2,1.2,NaN,7.2,6.3,3.5,3.2,6.0,5.1,1.3,1.3
16,Iowa,"{'human_address': '{""address"":""Iowa"",""city"":""""...",3.2,3.0,NaN,NaN,5.9,4.6,2.9,3.4,5.1,4.8,NaN,NaN
17,Kansas,"{'human_address': '{""address"":""Kansas"",""city"":...",3.4,3.6,2.3,NaN,6.0,7.4,3.0,3.3,6.0,5.8,NaN,1.4
18,Kentucky,"{'human_address': '{""address"":""Kentucky"",""city...",4.0,3.9,1.8,2.0,7.2,7.8,3.7,3.4,6.5,6.5,1.5,1.3
19,Louisiana,"{'human_address': '{""address"":""Louisiana"",""cit...",5.2,5.4,2.8,1.8,8.6,9.4,5.1,5.7,8.3,9.1,2.4,1.9
20,Maine,"{'human_address': '{""address"":""Maine"",""city"":""...",3.8,3.3,NaN,NaN,NaN,NaN,2.8,3.1,6.6,5.1,NaN,NaN
21,Maryland,"{'human_address': '{""address"":""Maryland"",""city...",2.7,2.2,1.6,NaN,5.8,5.4,2.2,1.8,4.1,3.5,1.4,0.9
22,Massachusetts,"{'human_address': '{""address"":""Massachusetts"",...",1.8,1.9,NaN,NaN,3.3,4.0,1.7,1.8,2.7,3.1,0.9,0.9
23,Michigan,"{'human_address': '{""address"":""Michigan"",""city...",2.7,2.2,1.1,1.0,6.8,5.1,2.0,1.8,4.3,3.3,1.2,1.1
24,Minnesota,"{'human_address': '{""address"":""Minnesota"",""cit...",2.1,1.9,NaN,NaN,3.7,3.5,2.2,2.1,3.2,3.0,1.2,0.9
25,Mississippi,"{'human_address': '{""address"":""Mississippi"",""c...",6.1,6.0,2.6,2.8,12.0,10.8,5.7,5.8,9.8,9.4,2.7,2.8
26,Missouri,"{'human_address': '{""address"":""Missouri"",""city...",4.8,3.4,1.9,NaN,9.5,6.9,4.4,3.2,7.8,5.6,1.8,1.3
27,Montana,"{'human_address': '{""address"":""Montana"",""city""...",9.4,7.3,NaN,NaN,21.4,15.4,7.2,6.9,14.9,10.2,4.0,4.3
28,Nebraska,"{'human_address': '{""address"":""Nebraska"",""city...",4.0,3.3,NaN,NaN,6.5,7.0,3.5,3.0,6.4,5.0,NaN,NaN
29,Nevada,"{'human_address': '{""address"":""Nevada"",""city"":...",2.8,3.3,NaN,NaN,4.6,6.4,3.2,2.7,4.2,4.9,1.4,1.7
30,New Hampshire,"{'human_address': '{""address"":""New Hampshire"",...",2.4,2.4,NaN,NaN,NaN,NaN,2.9,NaN,4.1,3.2,NaN,NaN
31,New Jersey,"{'human_address': '{""address"":""New Jersey"",""ci...",1.8,1.8,NaN,NaN,4.6,3.6,1.4,1.7,2.9,2.9,0.9,0.8
32,New Mexico,"{'human_address': '{""address"":""New Mexico"",""ci...",4.8,5.7,NaN,NaN,9.1,11.2,4.5,5.1,6.9,8.6,2.9,2.8
33,New York,"{'human_address': '{""address"":""New York"",""city...",1.7,1.6,0.6,0.7,3.3,3.0,1.7,1.5,2.7,2.4,0.8,0.8
34,North Carolina,"{'human_address': '{""address"":""North Carolina""...",4.2,3.8,1.7,1.4,8.0,7.7,4.0,3.6,6.8,6.3,1.7,1.5
35,North Dakota,"{'human_address': '{""address"":""North Dakota"",""...",11.3,7.2,NaN,NaN,15.3,15.2,12.0,6.1,17.4,10.7,NaN,NaN
36,Ohio,"{'human_address': '{""address"":""Ohio"",""city"":""""...",3.5,2.7,1.2,0.8,6.8,5.6,3.3,2.6,5.5,4.2,1.6,1.3
37,Oklahoma,"{'human_address': '{""address"":""Oklahoma"",""city...",5.6,4.0,NaN,NaN,10.5,7.4,5.8,3.9,9.3,6.0,1.9,2.1
38,Oregon,"{'human_address': '{""address"":""Oregon"",""city"":...",2.2,2.5,NaN,NaN,5.2,4.2,1.8,2.6,3.1,3.7,1.3,1.4
39,Pennsylvania,"{'human_address': '{""address"":""Pennsylvania"",""...",3.3,2.7,1.4,0.7,7.2,5.5,2.8,2.7,5.4,4.4,1.3,1.1
40,Rhode Island,"{'human_address': '{""address"":""Rhode Island"",""...",2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,South Carolina,"{'human_address': '{""address"":""South Carolina""...",7.6,5.8,2.8,2.0,14.2,12.4,7.6,5.3,12.3,9.0,3.2,2.9
42,South Dakota,"{'human_address': '{""address"":""South Dakota"",""...",5.7,5.6,NaN,NaN,NaN,NaN,NaN,6.2,7.4,8.7,NaN,NaN
43,Tennessee,"{'human_address': '{""address"":""Tennessee"",""cit...",4.6,4.1,1.6,NaN,8.0,8.2,4.9,4.1,7.5,6.8,1.8,1.5
44,Texas,"{'human_address': '{""address"":""Texas"",""city"":""...",4.9,5.4,2.1,2.3,10.0,10.0,4.7,5.3,7.6,8.1,2.4,2.7
45,Utah,"{'human_address': '{""address"":""Utah"",""city"":""""...",1.2,2.0,NaN,NaN,NaN,NaN,1.9,2.3,1.7,3.0,NaN,NaN
46,Vermont,"{'human_address': '{""address"":""Vermont"",""city""...",3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Virginia,"{'human_address': '{""address"":""Virginia"",""city...",2.5,2.5,1.2,1.2,4.5,5.1,2.6,2.3,4.1,3.9,0.9,1.2
48,Washington,"{'human_address': '{""address"":""Washington"",""ci...",2.1,1.9,NaN,NaN,4.0,3.4,2.0,1.9,3.6,2.9,0.7,0.9
49,West Virginia,"{'human_address': '{""address"":"""",""city"":""West""...",5.6,4.7,NaN,NaN,12.9,10.0,4.4,4.0,9.3,7.1,NaN,NaN
50,Wisconsin,"{'human_address': '{""address"":""Wisconsin"",""cit...",3.6,2.9,1.6,NaN,6.5,7.5,3.5,2.3,5.6,4.8,1.6,1.2
51,Wyoming,"{'human_address': '{""address"":""Wyoming"",""city""...",7.1,8.2,NaN,NaN,17.3,NaN,NaN,8.1,11.3,13.1,NaN,NaN

In [5]:
data.describe()

,"All Ages, 2012","All Ages, 2014","Ages 0-20, 2012","Ages 0-20, 2014","Ages 21-34, 2012","Ages 21-34, 2014","Ages 35+, 2012","Ages 35+, 2014","Male, 2012","Male, 2014","Female, 2012","Female, 2014"
count,50.000000,49.000000,24.000000,18.000000,42.000000,41.000000,46.000000,46.000000,48.000000,48.000000,35.000000,35.000000
mean,3.916000,3.624490,1.620833,1.411111,7.971429,7.173171,3.584783,3.536957,6.270833,5.658333,1.662857,1.600000
std,1.947092,1.581604,0.647389,0.635137,3.833249,3.014882,1.896543,1.568490,3.101472,2.425821,0.759290,0.772315
min,1.200000,1.600000,0.600000,0.700000,3.300000,3.000000,1.400000,1.500000,1.700000,2.400000,0.700000,0.800000
25%,2.500000,2.500000,1.200000,0.850000,5.800000,5.200000,2.200000,2.350000,4.100000,3.700000,1.150000,1.100000
50%,3.600000,3.200000,1.600000,1.200000,6.850000,6.300000,3.200000,3.100000,5.700000,4.900000,1.500000,1.300000
75%,4.800000,4.600000,1.950000,1.950000,9.400000,8.200000,4.375000,4.475000,7.525000,7.125000,1.850000,1.800000
max,11.300000,8.200000,2.800000,2.800000,21.400000,15.400000,12.000000,8.100000,17.400000,13.100000,4.000000,4.300000

In [9]:
data.isnull().sum()

State                0
Location             0
All Ages, 2012       2
All Ages, 2014       3
Ages 0-20, 2012     28
Ages 0-20, 2014     34
Ages 21-34, 2012    10
Ages 21-34, 2014    11
Ages 35+, 2012       6
Ages 35+, 2014       6
Male, 2012           4
Male, 2014           4
Female, 2012        17
Female, 2014        17
dtype: int64

In [10]:
data.shape()

TypeError: 'tuple' object is not callable

In [1]:
sns.pairplot(data, x_vars=feature_cols, y_vars='total_rentals');

NameError: name 'sns' is not defined